### PR TITLE
Specify maintainer in Dockerfile

### PR DESCRIPTION
**Pull request by ivanrome**
As seen in https://www.codacy.com/app/ivanrome/docker-elk/issues

### CODE REVIEW

**Comment by antoineco** [comment]
Since the image is built by the end user and not the repo authors, shouldn't be/she the maintainer?

**Comment by ivanrome** [comment]
It's true dockerfile is minimal and just a FROM clause exists.

Maybe the mainteiner should be elastic.co

**Comment by antoineco** [comment]
Yes, it is already:
https://github.com/elastic/elasticsearch-docker/blob/master/templates/Dockerfile.j2#L109

**Comment by ivanrome** [comment]
Yes, but that file is not in the project but in the source image.

**Comment by deviantony** [comment]
I agree with @antoineco here, we provide simple wrapper around the official images in order to make the stack quite extensible. We don't really maintain any Docker images in here (nothing is hosted on any registry).

And if we wanted to add maintainers, I'd see my name as well as @antoineco's name (thanks again for the great job :+1:)

**Comment by antoineco** [comment]
Closing this, but thanks for the proposal @ivanrome, hopefully it will come in handy for someone even if we don't merge it here.

**Pull request closed without merging**
