### PR TITLE
Use new official images (Search Guard)

### PR DESCRIPTION
**Pull request by antoineco**
Do not merge yet, I get the following error in Kibana:
```
Unhandled rejection Error: Plugin hapi-auth-cookie already registered in: http://0.0.0.0:5601
```

@floragunncom do you have any clue why?

ref #95 #96

### CODE REVIEW

**Comment by floragunncom** [comment]
will have a look

**Comment by floragunncom** [comment]
https://github.com/elastic/kibana-docker does already have x-pack pre-installed

**Comment by antoineco** [comment]
Yes, but X-Pack is disabled via env vars. Does it overlap?

**Comment by floragunncom** [comment]
you only disabled it for elasticsearch, not kibana. not sure if this is possible.

**Comment by floragunncom** [comment]
guess we need the disable config props also in kibana.yml

**Comment by antoineco** [comment]
It's disabled for Kibana in the Docker Compose file  as well. I'll check if I left something behind.

**Comment by deviantony** [comment]
@antoineco @floragunncom tell me when this is ready to merge.

**Comment by deviantony** [comment]
@antoineco so is it ready to merge?

**Comment by antoineco** [comment]
Yup!

**Comment by deviantony** [comment]
Nice !
Thanks for the amazing work @antoineco ! :trophy: :clap:

**Comment by floragunncom** [comment]
Great work!

**Pull request merged**
