### PR TITLE
Move CI flow from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by antoineco**
GitHub now has its own CI called _GitHub actions_ embedded into code repositories, and after playing with it a little bit I have to say I really like it! It's fast and quite similar to Travis, with a large catalog of "actions" and some neat integrations with Git repos.

This PR moves the CI pipeline from Travis CI to GitHub Actions, without changing the existing test logic. I had to rewrite the util functions though, to make things more portable and avoid assuming everything listens on `localhost`.

All runs, including the ones triggered by the PR, can be seen by clicking the `Actions` tab in the top bar ([here](https://github.com/deviantony/docker-elk/actions)).

### CODE REVIEW

**Comment by antoineco** [comment]
Marking as draft until I figure why `expect` fails on `bin/elasticsearch-setup-passwords` with code `78` in Swarm mode.

**Comment by antoineco** [comment]
Fixed: https://github.com/deviantony/docker-elk/issues/455#issuecomment-708035654

**Comment by deviantony** [comment]
@antoineco I see I'm assigned to this one, do you want me to review it? Overall I agree with the use of Github actions as well.

**Comment by antoineco** [comment]
@deviantony it was mostly for visibility, so that you can disable the Travis integration in the repo if you want.

The current run should pass, and then we should be good to merge.

**Comment by deviantony** [comment]
Allgood I'll get rid of the Travis integration after this PR is merged.

Great job :+1:

**Comment by antoineco** [comment]
Thanks for the quick check! 🙌

**Comment by deviantony** [comment]
I removed the Travis webhook, I think it's the only thing that was setup re Travis (no integration).

**Pull request merged**
