### PR TITLE
rename logstatch config to match how it's going to be mapped in the container

### PR DESCRIPTION
**Pull request by jvinod**
Sometimes a git repo can serve as a source for config - it is advantageous to layout the git repo exactly how it gets mapped in the container. Renaming this to conf.d instead of config allows me to directly mount the git repo at /etc/

### CODE REVIEW

**Comment by deviantony** [comment]
I'm not quite sure I should merge this PR.

One of the main goal of this project is simplicity and I've got the feeling that using the same configuration layout for the containers is helping to reach that goal.

**Comment by deviantony** [comment]
Still open for the moment, if anybody else think that this PR should be merged, please discuss it there.

**Comment by HunterGerlach** [comment]
Both points are valid, but overall consistency for the end user is the goal of this project, so I don't think this should be merged.

**Comment by antoineco** [comment]
@jvinod the logstash configuration path is now closer to how it is mapped inside the container. Is this PR still relevant?

**Comment by deviantony** [comment]
IMO it's pretty old and should be closed.

**Pull request closed without merging**
