### PR TITLE
Update to Elastic 7.0.1

### LINKED ISSUE #390: 7.x support?
Will this work with the 7.x (currently 7.0.1) stack?   What's the timeline for that becoming the new default?

### PR DESCRIPTION
**Pull request by kg-ops**
* [Elasticsearch 7.0.1 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/release-notes-7.0.1.html)
* [Kibana 7.0.1 Release Notes](https://www.elastic.co/guide/en/kibana/7.0/release-notes-7.0.1.html)
* [Logstash 7.0.1 Release Notes](https://www.elastic.co/guide/en/logstash/7.0/logstash-7-0-1.html)

[Blog post](https://www.elastic.co/blog/elastic-stack-7-0-0-released?elektra=products&storm=main)

Closes #390

### CODE REVIEW

**Comment by sdellenb** [comment]
Just FYI - I've been running the stack on 7.0.0 since Friday and every night when Logstash wants to roll over the index, it stops working with this message:
```
[2019-04-14T00:00:01,445][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-2019.04.14", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x5b565b59>], :response=>{"index"=>{"_index"=>"logstash-2019.04.14", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"The [default] mapping cannot be updated on index [logstash-2019.04.14]: defaults mappings are not useful anymore now that indices can have at most one type."}}}}
```
I searched my configuration up and down and through the containers but I cannot find a defaults mapping setting. Yesterday, I created the logstash-2019.04.13 index manually and it worked again until the roll over tonight.

I'm quite new to Elastic Search and use it to mirror my rsyslogs to a searchable database (so nothing critical is lost), but I find it quite frustrating to debug such issues.

**Comment by antoineco** [comment]
@sdellenb did you start a new Stack or upgrade from 6.7? My gut feeling is that the Logstash [index template](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-templates.html) may have changed between the 2 versions and needs to be replaced.

**Comment by sdellenb** [comment]
I upgraded from 6.7, with the same changes as this PR (except the port). I'll check the index template.

**Comment by antoineco** [comment]
@sdellenb the release notes mention [the field reference parser is now more strict](https://www.elastic.co/guide/en/logstash/7.0/breaking-7.0.html#field-ref-strict). Are you using a specific plugin to ship your logs to Logstash?

**Comment by sdellenb** [comment]
No plugin, just an rsyslog template generating a JSON for logstash.
I've managed to get it working again by updating the **_index template_** with a simplified version of the mappings of the current index as posted above. Thanks for the hint! 👍 

On a different note regarding the upgrade to 7.0.0:
[discovery.zen.minimum_master_nodes](https://github.com/deviantony/docker-elk/blob/master/elasticsearch/config/elasticsearch.yml#L11) has been deprecated.
I'd have no idea how to address it, but so far it doesn't break anything.

**Comment by antoineco** [comment]
Thanks for the feedback, much appreciated  🙏  We'll have to address this in the default configuration indeed.

**Comment by antoineco** [comment]
@kg-ops 7.0.1 is out. Would you mind updating the PR so we can test the upgrade path from 6.7.x?

**Pull request merged**
