### PR TITLE
Added restart: unless-stopped to the docker-compose.yml

### PR DESCRIPTION
**Pull request by HristoKolev**
In order to start after server reboot. :)

### CODE REVIEW

**Comment by antoineco** [comment]
@HristoKolev thanks for the contribution!

I am not certain this would be a sensible default. Personally, I wouldn't want random Compose stacks to restart on my machine without me knowing. If I _do_ want to enable it, I add it to my own local copy or fork, without forcing all users to adopt my own preferences.

@deviantony opinions on that one?

**Comment by HristoKolev** [comment]
Well, in my opinion, when I `docker-compose up -d` something I expect it to stay up until I say so.

Maybe that's just me. :)

**Comment by HristoKolev** [comment]
I didn't realize how famous this repo is. If nobody has raised this issue up until now , then I must be in the wrong.

**Comment by antoineco** [comment]
That holds true if you run the stack in a server setup, where it needs to be available all the time.

Now imagine using this locally, for backing a development flow that uses the Elastic stack. You will probably want your containers to be running when you're actively working on that project, but when you're not, I'm sure what you'd prefer giving back 2 GB of RAM to your workstation for other purposes.

Like you said the project is popular, so we need to keep it neutral by default, but easily extensible.

**Comment by deviantony** [comment]
> If I do want to enable it, I add it to my own local copy or fork, without forcing all users to adopt my own preferences.

Agree, I do not consider this one as a sensible default either.

**Pull request closed without merging**
