### PR TITLE
Upgrade to Version 6.5.2

### LINKED ISSUE #338: Update to 6.5.2
* [Elasticsearch 6.5.2 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/release-notes-6.5.2.html)
* [Logstash 6.5.2 Release Notes](https://www.elastic.co/guide/en/logstash/current/logstash-6-5-2.html)
* [Kibana 6.5.2 Release Notes](https://www.elastic.co/guide/en/kibana/current/release-notes-6.5.2.html)

### PR DESCRIPTION
**Pull request by mrnonz**
Fixes #338

### CODE REVIEW

**Comment by antoineco** [comment]
Thanks! Don't forget line 130 (c.f. 9bbd587aecf6d3d1fbf4044b55227dda4060b854)

**Comment by mrnonz** [comment]
> Thanks! Don't forget line 130 (c.f. [9bbd587](https://github.com/deviantony/docker-elk/commit/9bbd587aecf6d3d1fbf4044b55227dda4060b854))

I think it's has already fix.

thanks,

**Comment by antoineco** [comment]
It's not a "fix", without the change on line 130 the documentation is not accurate and users will get an error when they try to create the index pattern from their shell.

**Comment by antoineco** [comment]
My bad!

**Pull request merged**
