### PR TITLE
Add redis queue to elk stack

### PR DESCRIPTION
**Pull request by rgroten**
Added a redis container to act as message queue

### CODE REVIEW

**Comment by deviantony** [comment]
Hello, thanks for the contribution but I'm not sure that the default stack should be using a more complex setup than using only the ELK components.

I could ponder a way using branches to expose multiple working setups and document it in the README.

I'll keep the PR open till I found a solution.

**Comment by rgroten** [comment]
No problem, I needed it for my solution and thought I'd share it in case you're interested!  Your project was extremely useful btw.

**Comment by deviantony** [comment]
Thanks :+1: 

As I said, this could be interesting to have people sharing their working configurations on another branch/something, I need to think about this a little.

**Comment by deviantony** [comment]
I'll close this PR, your work should be referenced somewhere else.

**Comment by mskutin** [comment]
@deviantony why you won't just merge this into a separate branch? 

> I could ponder a way using branches to expose multiple working setups and document it in the README. 

 I think it's a good idea to keep multiple scenarios in one repo, you can split the `default` elk stack, keep it in main branches and create subdirectories for the Vagrant, Redis, etc.

**Comment by deviantony** [comment]
The discussion about branches/wiki/files is opened in #33. Not decision at the moment.

**Pull request closed without merging**
