### PR TITLE
Use vagrant to run ELK

### PR DESCRIPTION
**Pull request by wizardbyron**

### CODE REVIEW

**Comment by wizardbyron** [comment]
Prerequisite: install [Vagrant](https://www.vagrantup.com/downloads.html) and [VirtualBox](https://www.virtualbox.org/wiki/Downloads).
 ```bash
git clone git@github.com:wizardbyron/docker-elk.git
cd docker-elk
vagrant up
```

**Comment by mskutin** [comment]
:+1:

**Comment by deviantony** [comment]
I'm not sure about the interest of using Vagrant to use the stack. It seems to me that it would just replace the Docker installation by the Vagrant installation.

Honestly, after having played with Vagrant for a few months, once I installed Docker I've never used Vagrant anymore.

**Comment by wizardbyron** [comment]
It provides an option to some users who need to run ELK in vagrant.

**Comment by deviantony** [comment]
All right, I guess that I could merge that one into a custom branch ! Could you update the README to add the prerequisites?

**Comment by wizardbyron** [comment]
Updated the README.md.

**Comment by deviantony** [comment]
Nice, I've pushed a new branch called `vagrant`, could you rebase your PR to this branch?

**Comment by wizardbyron** [comment]
I created new PR to new branch. https://github.com/deviantony/docker-elk/pull/47

**Pull request closed without merging**
