### PR TITLE
Explain the project's philosophy

### PR DESCRIPTION
**Pull request by antoineco**
I tried to explain the project's philosophy in 2 short sentences, so that its aim is clear to people who visit the repo. @deviantony what do you think?

The reference to "elastdocker" is optional. I though it would be nice to provide an example of project that forked this repo and added some bells and whistles to it (lots of opinionated parameters, etc.).

### CODE REVIEW

**Review by deviantony — APPROVED** [review]
Good idea and clear philosophy which I agree with :+1: 

Not clear if elastdocker is an actual fork of this repository but good example nonetheless.

**Comment by antoineco** [comment]
I wasn't 100% sure either, but then Google returned this thread where the author mentions:

> This project is a collection of everything I added on `deviantony/docker-elk` to start a small scale dockerized elk stack.
>
> -- https://www.reddit.com/r/devops/comments/db3cw7/comment/f1zajgw

**Comment by deviantony** [comment]
Yes IMO it's fine and it's a good example. You can merge it.

**Comment by antoineco** [comment]
Thanks for the review!

**Pull request merged**
