### PR TITLE
Update .env

### LINKED ISSUE #483: Update to 7.6.2
* [Elasticsearch 7.6.2 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.6.2.html)
* [Kibana 7.6.2 Release Notes](https://www.elastic.co/guide/en/kibana/current/release-notes-7.6.2.html)
* [Logstash 7.6.2 Release Notes](https://www.elastic.co/guide/en/logstash/current/logstash-7-6-0.html)

### PR DESCRIPTION
**Pull request by alkanarslan**
Closes #483

### CODE REVIEW

**Comment by antoineco** [comment]
Thanks @alkanarslan! Looks like the tests are green 👍 

Before we merge this, could you please also update the `README.md` and `docker-stack.yaml` files accordingly? See an example here: [Update to 7.6.0](https://github.com/deviantony/docker-elk/commit/c680149e428f14d0557ad7ed89bf8eab5c483328).

You can point the badge in the README to this PR, like:
```diff
- [![Elastic Stack version](https://img.shields.io/badge/ELK-7.6.0-blue.svg?style=flat)](https://github.com/deviantony/docker-elk/issues/473)
+ [![Elastic Stack version](https://img.shields.io/badge/ELK-7.6.2-blue.svg?style=flat)](https://github.com/deviantony/docker-elk/issues/482)
```

**Comment by antoineco** [comment]
@deviantony I think the integration with Travis CI may be broken, tests failures are not reported inside PRs anymore.

**Comment by deviantony** [comment]
@antoineco RIP Travis. Something changed recently in our travis config? I'll investigate the repo settings.

**Comment by antoineco** [comment]
Right, the CI status is back, cheers!

**Pull request merged**
