### PR TITLE
Enable Search Guard enterprise trial by default

### PR DESCRIPTION
**Pull request by antoineco**
Same changes as in #387, but for Search Guard.

Closes #380
Closes #388

### CODE REVIEW

**Comment by deviantony** [comment]
cc @floragunncom for information

I'll try to review this today.

**Comment by antoineco** [comment]
I addressed comments from #387.

**Comment by deviantony** [comment]
@antoineco sorry for the late update. I've been able to give this a try locally and it's working fine. You can merge it.

**Comment by antoineco** [comment]
Noice :ok_hand:  Thanks for the review!

**Pull request merged**
