### PR TITLE
Release 5.6.3

### PR DESCRIPTION
**Pull request by brint**
Updates ELK images to 5.6.3

### CODE REVIEW

**Comment by antoineco** [comment]
Thanks @brint!

**Comment by gotjoshua** [comment]
Greetings,
I just made a [fork](https://github.com/dcomposed/elk) that uses an .env file to set the desired version. 
Works quite well - i'm running 6.0.0-rc1. 

Are you interested to integrate this strategy into your repo?

**Comment by brint** [comment]
Hi @gotjoshua - This PR was merged about a week ago, so I don't think people are going to be tracking comments here. It may be worth either popping an issue or making a PR to get feedback.

**Comment by deviantony** [comment]
@gotjoshua agree, please open an issue that it can be discussed.

**Pull request merged**
