### PR TITLE
Elk with Searchguard and Sentinl

### PR DESCRIPTION
**Pull request by parivero**
Hi,
I've extended your docker-elk repo by adding support for Sentinl. Be my guest to add this demo to your repo if you find it useful.

Regards.

### CODE REVIEW

**Comment by parivero** [comment]
Hi, I think it could be a new branch like SearchGuard and it would be a free approach to the ElasticSearch x-pack (which includes security, alerts and reports). In the future, someone could add the rest of the x-pack features.
In any case i can gladly create a new page in the wiki.

**Comment by antoineco** [comment]
The problem with new branches is that they have to be kept in sync manually by maintainers, because they can't be merged into one another.
This project tries to remain quite bare so that people can fork it and add their own plugins - like you did - without changing the Compose file or restructuring the repo. It's a boilerplate to build upon.
As nice as it would be to have one dedicated branch per popular plugin, it's simply not realistic without letting some branches rot over time (cf the `vagrant` branch).

If you add a Markdown file to this PR reusing the instructions and examples you already wrote, I will gladly add it to the Wiki for you.

**Comment by parivero** [comment]
First sorry for the delay. The file sentinl.md was added to PR.

Regards.

**Comment by antoineco** [comment]
@parivero It took me a while but I finally created the page and added your content to it (slightly rephrased): https://github.com/deviantony/docker-elk/wiki/Popular-integrations

Thanks a lot! 🙌 
Hopefully we'll see some other similar contributions :)

**Pull request closed without merging**
